export const PrimaryFont = 'Poppins';
export const FontStyle = {
  // exclude
  h1: {fontSize: 50, fontFamily: PrimaryFont},
  h2: {fontSize: 38, fontFamily: PrimaryFont},
  h3: {fontSize: 28, fontFamily: PrimaryFont},
  h4: {fontSize: 21, fontFamily: PrimaryFont},
  p: {fontSize: 16, fontFamily: PrimaryFont},
  small: {fontSize: 12, fontFamily: PrimaryFont},
  header1: {fontSize: 16, fontFamily: PrimaryFont, fontWeight: '800'},
  header2: {fontSize: 14, fontFamily: PrimaryFont, fontWeight: '700'},
  title1: {fontSize: 10, fontFamily: PrimaryFont, fontWeight: '700'},
  title2: {fontSize: 9, fontFamily: PrimaryFont, fontWeight: '700'},
  title3: {fontSize: 9, fontFamily: PrimaryFont, fontWeight: '600'},
  title4: {fontSize: 6, fontFamily: PrimaryFont, fontWeight: '600'},
  caption1: {fontSize: 8, fontFamily: PrimaryFont, fontWeight: '700'},
  caption2: {fontSize: 7, fontFamily: PrimaryFont, fontWeight: '600'},
  caption3: {fontSize: 8, fontFamily: PrimaryFont, fontWeight: '400'},

  //heading
  H1: {fontFamily: PrimaryFont, fontSize: 28},
  H1_extrabold: {fontFamily: PrimaryFont, fontSize: 28, fontWeight: '800'},
  H1_medium: {fontFamily: PrimaryFont, fontSize: 28, fontWeight: '500'},
  H1_semibold: {fontFamily: PrimaryFont, fontSize: 28, fontWeight: '600'},
  H1_bold: {fontFamily: PrimaryFont, fontSize: 28, fontWeight: '700'},
  H2: {fontFamily: PrimaryFont, fontSize: 23},
  H2_extrabold: {fontFamily: PrimaryFont, fontSize: 23, fontWeight: '800'},
  H2_medium: {fontFamily: PrimaryFont, fontSize: 23, fontWeight: '500'},
  H2_semibold: {fontFamily: PrimaryFont, fontSize: 23, fontWeight: '600'},
  H2_bold: {fontFamily: PrimaryFont, fontSize: 23, fontWeight: '700'},
  H3: {fontFamily: PrimaryFont, fontSize: 19},
  H3_extrabold: {fontFamily: PrimaryFont, fontSize: 19, fontWeight: '800'},
  H3_medium: {fontFamily: PrimaryFont, fontSize: 19, fontWeight: '500'},
  H3_semibold: {fontFamily: PrimaryFont, fontSize: 19, fontWeight: '600'},
  H3_bold: {fontFamily: PrimaryFont, fontSize: 19, fontWeight: '700'},
  H4: {fontFamily: PrimaryFont, fontSize: 16},
  H4_extrabold: {fontFamily: PrimaryFont, fontSize: 16, fontWeight: '800'},
  H4_medium: {fontFamily: PrimaryFont, fontSize: 16, fontWeight: '500'},
  H4_semibold: {fontFamily: PrimaryFont, fontSize: 16, fontWeight: '600'},
  H4_bold: {fontFamily: PrimaryFont, fontSize: 16, fontWeight: '700'},
  H5: {fontFamily: PrimaryFont, fontSize: 13},
  H5_extrabold: {fontFamily: PrimaryFont, fontSize: 13, fontWeight: '800'},
  H5_medium: {fontFamily: PrimaryFont, fontSize: 13, fontWeight: '500'},
  H5_semibold: {fontFamily: PrimaryFont, fontSize: 13, fontWeight: '600'},
  H5_bold: {fontFamily: PrimaryFont, fontSize: 13, fontWeight: '700'},

  //title
  Title_1: {fontFamily: PrimaryFont, fontSize: 11},
  Title_13: {fontFamily: PrimaryFont, fontSize: 11, fontWeight: '800'},
  Title_10: {fontFamily: PrimaryFont, fontSize: 11, fontWeight: '500'},
  Title_7: {fontFamily: PrimaryFont, fontSize: 11, fontWeight: '600'},
  Title_4: {fontFamily: PrimaryFont, fontSize: 11, fontWeight: '700'},
  Title_2: {fontFamily: PrimaryFont, fontSize: 10},
  Title_14: {fontFamily: PrimaryFont, fontSize: 10, fontWeight: '800'},
  Title_11: {fontFamily: PrimaryFont, fontSize: 10, fontWeight: '500'},
  Title_8: {fontFamily: PrimaryFont, fontSize: 10, fontWeight: '600'},
  Title_5: {fontFamily: PrimaryFont, fontSize: 10, fontWeight: '700'},
  Title_3: {fontFamily: PrimaryFont, fontSize: 9},
  Title_15: {fontFamily: PrimaryFont, fontSize: 9, fontWeight: '800'},
  Title_12: {fontFamily: PrimaryFont, fontSize: 9, fontWeight: '500'},
  Title_9: {fontFamily: PrimaryFont, fontSize: 9, fontWeight: '600'},
  Title_6: {fontFamily: PrimaryFont, fontSize: 9, fontWeight: '700'},

  //body
  Body: {fontFamily: PrimaryFont, fontSize: 8},
  Body_extrabold: {fontFamily: PrimaryFont, fontSize: 8, fontWeight: '800'},
  Body_medium: {fontFamily: PrimaryFont, fontSize: 8, fontWeight: '500'},
  Body_semibold: {fontFamily: PrimaryFont, fontSize: 8, fontWeight: '600'},
  Body_bold: {fontFamily: PrimaryFont, fontSize: 8, fontWeight: '700'},

  //caption
  Caption: {fontFamily: PrimaryFont, fontSize: 7},
  Caption_extrabold: {fontFamily: PrimaryFont, fontSize: 7, fontWeight: '800'},
  Caption_medium: {fontFamily: PrimaryFont, fontSize: 7, fontWeight: '500'},
  Caption_semibold: {fontFamily: PrimaryFont, fontSize: 7, fontWeight: '600'},
  Caption_bold: {fontFamily: PrimaryFont, fontSize: 7, fontWeight: '700'},
};

const Fonts = {};
