// num_of_shapes,
// num_of_unique_styles,
// num_of_unique_colors,
// num_of_unique_shapes,
// isAnimated = false,
// isRotated = false,
// hasPattern = false,

export default data = [
  {
    level: 1,
    scorePayload: 100,
    num_of_shapes: [3, 5],
    num_of_unique_styles: 2,
    num_of_unique_colors: 1,
    num_of_unique_shapes: 3,
    isRotated: false,
    isAnimated: false,
    hasPattern: false,
    rounds: 3,
  },
  {
    level: 2,
    scorePayload: 100,
    num_of_shapes: [5, 7],
    num_of_unique_styles: 3,
    num_of_unique_colors: 2,
    num_of_unique_shapes: 2,
    isRotated: false,
    isAnimated: false,
    hasPattern: false,
    rounds: 3,
  },
  {
    level: 3,
    scorePayload: 200,
    num_of_shapes: [5, 7],
    num_of_unique_styles: 2,
    num_of_unique_colors: 2,
    num_of_unique_shapes: 2,
    isRotated: false,
    isAnimated: false,
    hasPattern: true,
    rounds: 3,
  },
  {
    level: 4,
    scorePayload: 300,
    num_of_shapes: [7, 10],
    num_of_unique_styles: 3,
    num_of_unique_colors: 2,
    num_of_unique_shapes: 3,
    isRotated: false,
    isAnimated: false,
    hasPattern: true,
    rounds: 3,
  },
  {
    level: 5,
    scorePayload: 300,
    num_of_shapes: [10, 15],
    num_of_unique_styles: 3,
    num_of_unique_colors: 2,
    num_of_unique_shapes: 2,
    isRotated: true,
    isAnimated: false,
    hasPattern: true,
    rounds: 3,
  },
  {
    level: 6,
    scorePayload: 300,
    num_of_shapes: [10, 15],
    num_of_unique_styles: 3,
    num_of_unique_colors: 1,
    num_of_unique_shapes: 2,
    isRotated: true,
    isAnimated: true,
    hasPattern: false,
    rounds: 5,
  },
];
